src/OmniBase-Tests/ODBDatabaseTest.class.st
src/OmniBase-Tests/ODBPersistentDictionaryTest.class.st

Tests for ODBPersistentDictionary

Tests-ODBPersistentDictionary 

---

src/OmniBase-Tests/ODBBTreeDictionaryTest.class.st
src/OmniBase-Tests/ODBBTreeIndexDictionaryTest.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st

- Started ODBBTreeDictionaryTest, for now just tests creating one
- ODBBTreeIndexDictionaryTest with some tests

ODBBTreeDictionaryTest, ODBBTreeIndexDictionaryTest

---

src/OmniBase-Tests/ODBBTreeIndexDictionaryTest.class.st
src/OmniBase-Tests/ODBIdentityDictionaryTest.class.st
src/OmniBase-Tests/ODBPersistentDictionaryTest.class.st
src/OmniBase-Tests/ODBWeakValueIdentityDictionaryTest.class.st

add more tests for ODBBTreeIndexDictionary and ODBIdentityDictionary

tests for ODBBTreeIndexDictionary and ODBIdentityDictionary

---

src/OmniBase/ODBLockRegistry.class.st

- #reset was missing a new
- some categorizations

ODBLockRegistry missing #new

---

src/OmniBase-Tests/ODBCleanCodeTest.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBDeserializer.class.st
src/OmniBase/ODBMacFileStream.class.st
src/OmniBase/ODBObjectIdStack.class.st
src/OmniBase/ODBObjectIndexFile.class.st
src/OmniBase/ODBUnixFileStream.class.st
src/OmniBase/Object.extension.st

- add #testNoUnusedTemporaryVariablesLeft
- remove all unsed temps

 40-Trivial-clean-Unused-temps

---

src/OmniBase/ODBPreviousVersionError.class.st
src/OmniBase/ODBUnexpectedNetworkError.class.st

- remove two unused excpetions, one step for #42

Remove-ODBUnexpectedNetworkError-ODBPreviousVersionError

---

src/OmniBase/ODBMemoryReadStream.class.st
src/OmniBase/ODBMemoryWriteStream.class.st

This PR implements ODBMemoryWriteStream and ODBMemoryReadStream as wrappers wrapping the Pharo streams

MemoryStreams-as-Wrapper

---

src/OmniBase/BinaryFileStream.extension.st

we alread use #readInto:startingAt:count:, method us unused
fixes #63

remove unused BinaryFileStream>>#readInto:startingAt:for:

---

src/OmniBase/ODBExpiredProxyObject.class.st
src/OmniBase/ODBReference.class.st

add ignoreForCoverage to #halt and  #inspect

 CodeCoverage-Ignore-some

---

src/OmniBase/ODBSerializer.class.st

- use ifNil
- translate comments

TrivialClean-ODBSerializer

---

src/OmniBase/ODBLocalClient.class.st
src/OmniBase/Object.extension.st
src/OmniBase/OmniBase.class.st

- replace senders of #odbToDo with a flag
-  some ifNil refactorings

 Cleanup-Class-Omnibase 

---

src/OmniBase/ODBObjectIDDictionary.class.st

Just some code-critique driven optimization/cleanup

optimize ODBObjectIDDictionary  by using  ifNotNil:

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/ODBDeserializer.class.st

- ODBSerializationTest should re-initialize ODBDeserializer and ODBTypeCodes class variables
- simplify #classArray

 ODBSerializationTest-init-Serializerstate 

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/ODBEncodingStream.class.st

enhances #testSerializationString to check an empty string and 1-Character Strings

fix nextOneCharacterString to register, with tests

---

src/OmniBase/ODBFileStreamWrapper.class.st
src/OmniBase/ODBMemoryStreamWrapper.class.st
src/OmniBase/ODBPrimitiveEncodingStream.class.st

- add #subclassResponsibility methods or push up methods from ODBMemoryStreamWrapper
- tag ODBPrimitiveEncodingStream as Abstract

ODBPrimitiveEncodingStream-define-subclassResponsibility

---

src/OmniBase/ODBReference.class.st
src/OmniBase/ODBReferenceManager.class.st
src/OmniBase/Object.extension.st
src/OmniBase/OmniBase.class.st

- some ifNil refactoring
- implement loadFromStream: using loadFromStream:externalReferencesLoaderBlock:
- remove some methods that we call on Omnibase class exclusively

Small cleanup (ifNil, unused methods)

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/Array.extension.st
src/OmniBase/Association.extension.st
src/OmniBase/ByteArray.extension.st
src/OmniBase/Character.extension.st
src/OmniBase/Date.extension.st
src/OmniBase/Dictionary.extension.st
src/OmniBase/Fraction.extension.st
src/OmniBase/IdentityDictionary.extension.st
src/OmniBase/ODBEncodingStream.class.st
src/OmniBase/OrderedCollection.extension.st
src/OmniBase/ProcessorScheduler.extension.st
src/OmniBase/String.extension.st
src/OmniBase/Time.extension.st
src/OmniBase/UndefinedObject.extension.st

Association and ByteArray for now, I am going through all of them

fix serialization for subclasses

---

src/OmniBase/ODBClassManager.class.st
src/OmniBase/ODBClient.class.st
src/OmniBase/ODBForeignClient.class.st
src/OmniBase/ODBLocalClient.class.st

Just automatic ifNil transformations and some assignment out if ifTrue/ifFalse transformation

Some more automatic ifNil: transformations

---

src/OmniBase/ODBBTreeDictionaryAssociation.class.st
src/OmniBase/ODBClassDescription.class.st
src/OmniBase/ODBDBBTreeIndexDictionary.class.st
src/OmniBase/ODBDatabaseObject.class.st
src/OmniBase/ODBIdentityDictionary.class.st
src/OmniBase/ODBObjectID.class.st
src/OmniBase/ODBReference.class.st
src/OmniBase/ODBRootObjectDBHolder.class.st

- categories
- ifNil transform

Trivial Clean: categories and IfNil: transformations

---

src/OmniBase/BlockClosure.extension.st
src/OmniBase/BoxedFloat64.extension.st
src/OmniBase/Character.extension.st
src/OmniBase/Class.extension.st
src/OmniBase/False.extension.st
src/OmniBase/Fraction.extension.st
src/OmniBase/Integer.extension.st
src/OmniBase/ODBReference.class.st
src/OmniBase/ODBTransaction.class.st
src/OmniBase/Process.extension.st
src/OmniBase/ProcessorScheduler.extension.st
src/OmniBase/SmallFloat64.extension.st
src/OmniBase/Symbol.extension.st
src/OmniBase/SystemDictionary.extension.st
src/OmniBase/True.extension.st
src/OmniBase/UndefinedObject.extension.st

fixes #120
I am adding issue tracker entries for all that #flag:

add comments to #odbSerialize. 

---

src/OmniBase/ODBLock.class.st
src/OmniBase/ODBTransaction.class.st

- subclassresponsibility
- automatic ifNil: transforms

 ifNil-transform-05-09

---

src/OmniBase-Tests/ODBSerializationTest.class.st

add tests for byte, fixed, weak and word layouts. One part of #135

Tests-Layouts-1

---

src/OmniBase-Tests/ODBIdentityDictionaryTest.class.st
src/OmniBase-Tools/ODBIdentityDictionary.extension.st
src/OmniBase-Tools/package.st
src/OmniBase/ODBIdentityDictionary.class.st

- add ODBIdentityDictionary>>#associations and test
- add package Omninase-Tools
- add method that is a copy of the special inspector we have for Dictionary

Add special inspector pane for ODBIdentityDictionary

---

src/OmniBase/ODBBTreeIterator.class.st
src/OmniBase/ODBClientManager.class.st
src/OmniBase/ODBFile.class.st
src/OmniBase/ODBLocalTransaction.class.st
src/OmniBase/ODBLockRegistry.class.st
src/OmniBase/ODBObjectIndexFile.class.st

Another ifNil code critique cleanup

IfNotNilClean-05-12 

---

src/OmniBase-Tests/ODBCleanCodeTest.class.st
src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreePage.class.st
src/OmniBase/ODBEncodingStream.class.st
src/OmniBase/ODBIntegerSet.class.st

- fix testNoUnusedInstanceVariablesLeft to find class instance variables, too
- remove unused class ivar ODBEncodingStream
- some ifNil refactorings

 ifNil-05-17

---

src/OmniBase-Tests/ODBDatabaseTest.class.st
src/OmniBase-Tests/ODBGarbageCollectorTest.class.st
src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBGarbageCollector.class.st
src/OmniBase/ODBLocalTransaction.class.st
src/OmniBase/ODBObjectHolder.class.st
src/OmniBase/ODBObjectManager.class.st
src/OmniBase/ODBReferenceManager.class.st

- another automatic ifNil transform
- move testGC to the empty ODBGarbageCollectorTest

 IfNil-05-19

---

src/OmniBase/ODBBTreeIdentityDictionary.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBIdentityDictionary.class.st
src/OmniBase/ODBLocalTransaction.class.st
src/OmniBase/ODBReferenceManager.class.st

- some more #ifNil transforms
- add ODBIdentityDictionary>>#anySatisfy:
- use it to simplify ODBLocalTransaction>>#isChanged

ifNil-05-23 

---

src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBClientManager.class.st
src/OmniBase/ODBGcBTreeIterator.class.st
src/OmniBase/ODBLocalTransaction.class.st

 ifNil-05-24 

---

src/OmniBase/ODBBTreePage.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBObjectHolder.class.st
src/OmniBase/ODBSizeHolder.class.st
src/OmniBase/ODBValueHolder.class.st

 ifNil-05-29

---

src/OmniBase-Tests/ODBSerializationTest.class.st

finish adding a dedicated test for each layout. CompiledMethodLayout and EmphemeronLayout are skipped and marked as TODO
fixes #135

135-Tests-Make-sure-to-have-one-test-for-every-Class-Layout

---

src/OmniBase/BlockClosure.extension.st
src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreeIdentityDictionary.class.st
src/OmniBase/ODBLocalClient.class.st
src/OmniBase/ODBReferenceManager.class.st
src/OmniBase/ODBTransactionFile.class.st

ifNil-07-01 

---

src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreeIdentityDictionary.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBIdentityDictionary.class.st
src/OmniBase/ODBOldHoldersFile.class.st
src/OmniBase/ODBReference.class.st
src/OmniBase/ODBTransactionFile.class.st
src/OmniBase/ODBVersionDescriptor.class.st
src/OmniBase/Object.extension.st

ifNotNil-07-11

---

src/OmniBase/ODBBTreeDictionary.class.st

Translate a comment
