src/OmniBase-Tests/OmniBaseTest.class.st

This will remove the need to select the package under test when running tests with coverage analysis

add #packageNamesUnderTest to simplify code coverage tool usage

---

src/OmniBase-Tests/ODBSerializerBugsTest.class.st
src/OmniBase/SmallFloat64.extension.st

This is a minimal change to fix Small Float Serialization.
- add testSerializationSmallFloat64Two. This tests the scenario that failed *and* tests that the old serialized Floats can be still read
- make that SmallFloat64 implements #odbSerialize:, not odbBasicSerialize:
This fix follows the style used in the rest of the code. We should open an issue to refactor and document #odbBasicSerialize:
fixes #22

22-Persisting-an-OGCPoint-with-same-lat-and-lon-value-is-not-properly-read-back

---

src/OmniBase/ODBBTreeMultiValueDictionary.class.st
src/OmniBase/ODBExpiredProxyObject.class.st
src/OmniBase/ODBReference.class.st

This PR removes the methods
- #defaultLabelForInspector and #inspectorClass. Not used anymore, no senders
- moved the content from a method COMMENT to the class comment of the class ODBBTreeMultiValueDictionary

Remove-unsent-inspectorMethods

---

src/OmniBase/ODBIdentityDictionary.class.st
src/OmniBase/ODBObjectIDDictionary.class.st
src/OmniBase/ODBSerializer.class.st

ODBIdentityDictionary defines a very odd method not found in any other dictionary in Pharo:  #at:ifAbsentPutValue:
This is the same as at:ifAbsentPut:, but not sending #value to the block/object to be added. This allows the user to not wrap the argument in a block, which is slow as the block is created at runtime.
In Pharo this is not needed, as we have implemented #value on Object. This allows us to use the "no block" pattern with at:ifAbsentPut:
This PR 
- changes the one sender 
-  ODBIdentityDictionary should implement  at:ifAbsentPut:

Cleanup-atIfAbsentPutValue

---

src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreeIdentityDictionary.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBBTreeIntegerIndexDictionary.class.st
src/OmniBase/ODBBTreeIterator.class.st
src/OmniBase/ODBBTreeMultiValueDictionary.class.st
src/OmniBase/ODBChange.class.st
src/OmniBase/ODBChangesPackage.class.st
src/OmniBase/ODBClassInfoFile.class.st
src/OmniBase/ODBClassManager.class.st
src/OmniBase/ODBClient.class.st
src/OmniBase/ODBClientTable.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBContainerInfoFile.class.st
src/OmniBase/ODBDatabaseObject.class.st
src/OmniBase/ODBIDTable.class.st
src/OmniBase/ODBLocalClient.class.st
src/OmniBase/ODBLocalTransaction.class.st
src/OmniBase/ODBMemoryWriteStream.class.st
src/OmniBase/ODBObjectHolder.class.st
src/OmniBase/ODBObjectIDDictionary.class.st
src/OmniBase/ODBObjectIndexFile.class.st
src/OmniBase/ODBObjectManager.class.st
src/OmniBase/ODBSerializer.class.st
src/OmniBase/ODBSortedDictionary.class.st
src/OmniBase/ODBTransaction.class.st
src/OmniBase/ODBTransactionFile.class.st
src/OmniBase/OmniBase.class.st

- categorize all #initialize method correctly
- remove useless comment   "Private - Initialize receiver."
- add a flag: to one initialize with a code smell

Trivial Cleanup: categorize #initialize methods

---

src/OmniBase/ODBBTreeIntegerIndexDictionary.class.st
src/OmniBase/ODBChange.class.st
src/OmniBase/ODBChangesPackage.class.st
src/OmniBase/ODBClassManager.class.st
src/OmniBase/ODBClient.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBMemoryWriteStream.class.st
src/OmniBase/ODBObjectHolder.class.st
src/OmniBase/ODBObjectID.class.st
src/OmniBase/ODBObjectIDDictionary.class.st
src/OmniBase/ODBObjectManager.class.st
src/OmniBase/ODBSerializer.class.st
src/OmniBase/ODBSortedDictionary.class.st
src/OmniBase/ODBTransaction.class.st
src/OmniBase/ODBTransactionObject.class.st
src/OmniBase/OmniBase.class.st

- remove all non-needed #new implementations
- categorize the remaining method correctly
ODBObjectHolder class>>#new is a bit odd,  but as the superclass overrides new to *not* do #iniialize,  it is correct
This PR removes thus all the cases where we were sending #initialize twice.

Cleanup #new: do not send #initialize twice

---

src/OmniBase-Tests/ODBCleanCodeTest.class.st
src/OmniBase/ODBChange.class.st
src/OmniBase/ODBExpiredProxyObject.class.st
src/OmniBase/ODBFile.class.st
src/OmniBase/ODBReference.class.st
src/OmniBase/ODBTransactionObject.class.st

- remove the duplicated methods
- add #testNoDuplicatedMethodInHierarchy so we do not add more later
Fixes #41

41-Trivial-Clean-Duplicated-methods-in-the-hierarchy

---

src/OmniBase-Tests/ODBPersistentDictionaryTest.class.st
src/OmniBase/ODBExpiredProxyObject.class.st
src/OmniBase/ODBPersistentDictionary.class.st
src/OmniBase/ODBReference.class.st
src/OmniBase/Object.extension.st

- #isImmediate was renamed  isImmediateObject in Pharo
- #odbGetTransaction is called only by #markDirty, which has no senders
- Any other use is *storing* in ODBPersistentDictionary, thus reading existing PersistentDictionary instances should not be impacted
- #isImmediateObject is implemented in ProtoObject, so the proxy classes do not need to re-implement
- add ODBPersistentDictionaryTest>>#testAddImmediateObject
fixes #32

Fix 32: #isImmediate

---

src/OmniBase-Tests/ODBConcurrentTest.class.st
src/OmniBase-Tests/ODBDatabaseTest.class.st
src/OmniBase-Tests/ODBDiskBasedTest.class.st
src/OmniBase-Tests/ODBLockRegistryTest.class.st
src/OmniBase-Tests/ODBObjectManagerTest.class.st
src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBKeyLock.class.st
src/OmniBase/ODBLocalTransaction.class.st
src/OmniBase/ODBLock.class.st
src/OmniBase/ODBLockRegistry.class.st
src/OmniBase/ODBObjectID.class.st
src/OmniBase/ODBObjectLock.class.st
src/OmniBase/ODBTerminatedTransaction.class.st
src/OmniBase/ODBTransaction.class.st
src/OmniBase/ODBTransactionManager.class.st
src/OmniBase/ODBTransactionObject.class.st
src/OmniBase/OmniBase.class.st

The original omnibase relied locking completely on filesystem locking. In the windows systems back then locking was always mandatory, meaning the full file was locked. Early users of omnibase fiddled with the mandatory locking option in linux systems.
The semantics of fcntl() in *nix systems is that it is capable of locking resources between processes. This means two processes locking the same resource will fail. But the semantics are as well that within a process you cannot have that lock because it is expected that the process knows better how to organize concurrency.
This PR is an attempt to move locks from within a transaction to a global image structure. This can then be checked and locking conflicts can be detected before going to disk. This will then also work if multiple omnibase …

Introduce image wide lock registry

---

src/OmniBase/ODBExpiredProxyObject.class.st
src/OmniBase/ODBReference.class.st

- becomeForward: is already implemented in the superclass
ODBExpiredProxyObject and ODBReference
- implement #halt and #inspect exactly the same as the method we have in Object

Cleanup ODBExpiredProxyObject

---

src/OmniBase/ODBFileStream.class.st
src/OmniBase/ODBMacFileStream.class.st
src/OmniBase/ODBMemoryReadStream.class.st
src/OmniBase/ODBMemoryWriteStream.class.st
src/OmniBase/ODBStream.class.st
src/OmniBase/ODBUnixFileStream.class.st

This is a cleanup of ODBFileStream. It used to have (broken) support for non-Win, non-Unix, non-Mac.
This PR instead raises an Error and removes all the dead code.
in addititon:
- use error intead of halt
- some recategorizations 
- some subclassresponsibility
Fixes https://github.com/ApptiveGrid/MoniBase/issues/13
Fixes https://github.com/ApptiveGrid/MoniBase/issues/8

Cleanup ODBStream other Platforms

---

src/OmniBase-Tests/ODBDatabaseTest.class.st
src/OmniBase/BinaryFileStream.extension.st
src/OmniBase/ODBMacFileStream.class.st
src/OmniBase/ODBUnixFileStream.class.st

remove the VM bug workaround for #size.
Interestingly, after this #testBackup is green
fixes #57
fixes #11

 57--ODBUnixFileStreamsize-has-VM-bug-Workaround

---

src/OmniBase/ODBFileStream.class.st
src/OmniBase/ODBMemoryReadStream.class.st
src/OmniBase/ODBMemoryWriteStream.class.st
src/OmniBase/ODBStream.class.st

ODBStream managed a position variable that it had to keep in sync with the position of the BinaryFilesStream.
This PR:
- removes position from ODBStream, add it to the ODBMemory Streams
- #position now reports the position of the BinaryFilesStream
This PR does not yet rename the variable "fileHandle" to make reviewing easier

 ODBStream: do not manage position information

---

src/OmniBase/OmniBase.class.st

- #classManagerClass is not needed: it is only used in one place, so subclasses can just override that method if they want to use another class 
- Some code critique directed cleanup on the class side (use ifNotNil,  recategorize a method)

Small Cleanup of class Omnibase

---

src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBFile.class.st
src/OmniBase/ODBFileStream.class.st
src/OmniBase/ODBGarbageCollector.class.st

object space data file switch and lock waiting was not appropriate. Untangled loops and dependencies to switch a data file once and be able to unlock the same file that has been locked

[WIP] Fix gc and datafile locking

---

src/OmniBase/ODBAssociationChanged.class.st
src/OmniBase/ODBChange.class.st
src/OmniBase/ODBChangesPackage.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBDictionaryChanged.class.st
src/OmniBase/ODBGarbageCollectorRequest.class.st
src/OmniBase/ODBNewObjectVersion.class.st
src/OmniBase/ODBSizeChanged.class.st
src/OmniBase/ODBValueHolder.class.st
src/OmniBase/OmniBase.class.st

This PR does a small critique rule-driven cleanup of the RBChange hierarchy
- categorize subclasses the same as the superclass
- do not use #isNil

 isNil-cleanup-ODBChange

---

src/OmniBase/ODBFileStream.class.st
src/OmniBase/ODBMacFileStream.class.st
src/OmniBase/ODBMemoryReadStream.class.st
src/OmniBase/ODBMemoryWriteStream.class.st
src/OmniBase/ODBStream.class.st
src/OmniBase/ODBUnixFileStream.class.st
src/OmniBase/ODBWin32FileStream.class.st

- move ivar stream to ODBStream
- use it instead of fileHandle
- cleanup not-needed methods
The only not-that-nice aspect is that in ODBWin32FileStream, stream is now used for a filehandle.
fixes  #61

ODBStream: push up stream var

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/ByteArray.extension.st

This PR implements special serialization and deserialization for ByteArrays. This should save some space when storing them.
fixes #23
This is backward compatible, old serialized ByteArrays are stored as standard objects and will deserialize as such.

23-Serializer-ByteArrays-are-not-stored-using-ODBByteArrayCode 

---

src/OmniBase-Tests/ODBBTreeIndexDictionaryTest.class.st
src/OmniBase/ODBBTreeDictionary.class.st
src/OmniBase/ODBBTreeIndexDictionary.class.st

- Implement isEmpty and size for ODBBTreeIndexDictionary
- copy down the old implementation to ODBBTreeDictionary (which has the concept of size)
- add tests for size and #isEmpty
fixes #17

 17-ODBBTreeIndexDictionaryisEmpty-is-broken 

---

src/OmniBase-Tests/ODBSerializationTest.class.st

The order of associations in the internal array created by
```
IdentityDictionary newFrom: { #test->2 . #now->4 }. 
```
is different between Pharo10 and Pharo9.
This PR changes the assert to allow both

Pharo10-testSerializationIdentityDictionary

---

src/OmniBase/ODBFileStream.class.st
src/OmniBase/ODBStream.class.st

ODBFileStream class>>lockingMutex is never called, the variable it access never accessed outside of the method

Cleanup-unused-lockingMutex

---

src/OmniBase/Class.extension.st
src/OmniBase/ODBBTreeIndexDictionary.class.st
src/OmniBase/ODBClassDescription.class.st
src/OmniBase/ODBPersistentDictionary.class.st
src/OmniBase/OmniBase.class.st

- Code critique clean of ODBPersistentDictionary (ifNil, categories)
- replace some [] with nil, as "nil value" is much faster than "[] value". (this is kind of a poor man's clean block... but it is even faster than the clean "[] value" will be)

Trivial Clean: ODBPersistentDictionary

---

src/OmniBase/Character.extension.st
src/OmniBase/Class.extension.st
src/OmniBase/False.extension.st
src/OmniBase/Fraction.extension.st
src/OmniBase/Integer.extension.st
src/OmniBase/ODBTransaction.class.st
src/OmniBase/ProcessorScheduler.extension.st
src/OmniBase/SmallFloat64.extension.st
src/OmniBase/Symbol.extension.st
src/OmniBase/SystemDictionary.extension.st
src/OmniBase/True.extension.st
src/OmniBase/UndefinedObject.extension.st

make sure to implement serialization in #odbBasicSerialize:, override in #odbSerialize: for the cases we do not want to register the object
Code coverage analysis of the serialization methods now look much better
fixes #29

 29-Refactoring-improve-odbSerialize-vs-odbBasicSerialize 

---

src/OmniBase-Tests/ODBConcurrentTest.class.st

Workaround:
add some more time to the delay in testBTreeKeyLocking and friends
This might fix the test failures if they are timing related

Increase-Wait-in-Test 

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/BoxedFloat64.extension.st
src/OmniBase/ODBTypeCodes.class.st

This PR implements serialization for BoxedFloats64, until know they have been saved as normal Objects, which wastes space.
-  in #initializeTypeCodes, we had two definition for ODBFloatCode, remove 46 and keep 40
- fix testSerializationBoxedFloat64
- implemet serialization.
Deserialisation is implemented in Float and used by both.
This is backward compatible, that is, we can still read Floats already stored in a database
(see end of testSerializationBoxedFloat64)

24-Serializer-Implement-Boxed-Float-Serialization

---

src/OmniBase/ODBVersionControlFile.class.st
src/OmniBase/ODBVersionDescriptor.class.st

Implement #hash to be in sync with #= , fixes #3

3-ODBVersionDescriptor-redefines--but-does-not-implement-hash

---

src/OmniBase/ODBObjectManager.class.st
src/OmniBase/String.extension.st

#unifyContainerName: is the only user of the String extension method #trimBlanks. This pr changes to use the method withBlanksCondensed

Cleanup-trimblanks

---

src/OmniBase/ODBEncodingStream.class.st
src/OmniBase/ODBFileStreamWrapper.class.st

#basicPosition: is not needed in ODBFileStreamWrapper: we can just do what #position does in the superclass.
in addition, remove the return from ODBEncodingStream>>position: so that all the #position: methods are in sync with the Streams in Pharo to return self.

ODBFileStreamWrapper-Cleanup-basicPosition 

---

src/OmniBase-Tests/ODBSerializationTest.class.st

- add tests for Float 0.0, -0.0, 1.0, #infinity and #negativeInfinity
- move backward compatibilty check to testSerializationSmallFloat64
testSerializationBoxedFloat64Infinity tests for equality, not identity. This will be fixed next (I think we need to register boxed floats...)
fixes 137

Add tests for special Floats (zero, one, infinity, negativeInfinity)

---

src/OmniBase/SmalltalkImage.extension.st

"Smalltalk globals" is special encoded, but not SmalltalkImage.
(and de-serializing  Smalltalk to "Smalltalk globals" would be wrong)

Remove SmalltalkImage #odbSeserialize:

---

src/OmniBase/ODBFileStreamWrapper.class.st

remove the not needed temp when using the mutex
fixes #126

126-Cleanup-check-all-method-using-critical-temp-not-needed-

---

src/OmniBase/ODBFileStreamWrapper.class.st
src/OmniBase/ODBMemoryStreamWrapper.class.st
src/OmniBase/ODBPrimitiveEncodingStream.class.st

- add #getBytesFor:len: in the superclass
- override it from ODBFileStreamWrapper to add the monitor
- ODBMemoryStreamWrapper now does not need to implement it anymore
An odd thing is the additional #flush on read... we should I think remove it later after making sure we flush after *write*.

clean up ODBFileStreamWrapper>>#basicGetBytesFor:len:

---

src/OmniBase-Tests/ODBDatabaseTest.class.st
src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/HashedCollection.extension.st

When we store a Set, it stores all the elements. But on re-load, we create new objects for both the set and the contained objects.
If the contained objects use #identityHash, we now have a Set that was created with different hashes. We, therefore, have to re-hash on load (or alternatively create a new Set, as we do with Dictionary).
This fixes the  problem for all subclasses of HashedCollection.

Rehash HashedCollections on de-serialization

---

src/OmniBase/ODBEncodingStream.class.st
src/OmniBase/ODBTypeCodes.class.st

 133-ODBNilCode-is-not-used-there-is-ODBUndefinedObjectCode-to-store-nil 

---

src/OmniBase-Tests/ODBSerializationTest.class.st

add test for closure and Process, the two objects we store an error string instead of the objects

Tests: Closure and Process

---

.github/workflows/build.yml

We removed it because we use features not available there

Remove Pharo8 from CI Run

---

src/OmniBase/ODBEncodingStream.class.st

We call it always on the ODBFileStreamWrapper, and encoding should not know about files
fixes #158

remove ODBEncodingStream>>#remove

---

src/OmniBase/ODBBTreeIterator.class.st
src/OmniBase/ODBClassManager.class.st
src/OmniBase/ODBContainer.class.st
src/OmniBase/ODBDBBTreeDictionary.class.st
src/OmniBase/ODBLocalTransaction.class.st
src/OmniBase/ODBLockRegistry.class.st
src/OmniBase/ODBTransaction.class.st
src/OmniBase/ODBTransactionManager.class.st
src/OmniBase/OmniBase.class.st

- it returns the block value, no need for temps
- move temp definiton into the critical block (avoids escaping var access)
- use nil instead of []
- some ifNil: transforms

anothe small cleanup around senders of #critical:

---

src/OmniBase/ODBEncodingStream.class.st

just leftovers from the Float encoding cleanup

remove unused #nextFloatAs100Integer and #nextFloatAsInteger

---

src/OmniBase/ODBFileStreamWrapper.class.st
src/OmniBase/ODBMemoryStreamWrapper.class.st
src/OmniBase/ODBPrimitiveEncodingStream.class.st

- do not implement getByte and getChar in ODBMemoryStreamWrapper
- instead implement them in ODBPrimitiveEncodingStream
- return nil explicity in ODBFileStreamWrapper>>#getByte to fix CodeCritique complaint

Cleanup-Streams-getChar-getByte

---

src/OmniBase-Tests/ODBSerializationTest.class.st

Improve the tests that serialize an object twice (Check Encoding)
This shows that Strings are stored via internal reference for the second object, while the others write the object again (see the open issues regarding the question if we should not register them if they are real objects (like Fraction).

Improve the tests that serialize an object twice (Check Encoding)

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/ODBEncodingStream.class.st
src/OmniBase/ODBTypeCodes.class.st

- as a class variable, typeCodeMapping should be uppercase
- use  .. Code for ODBMinusTwo ODBMinusOne, as we have ODBMinusThreeCode already

Unify names of class vars in ODBTypeCodes

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/Fraction.extension.st
src/OmniBase/ODBEncodingStream.class.st

- add tests for Scaled Decimal and Fraction
- make sure to register Fraction objects, as they are normal objects and should manage (internal) identity
- this makes sure that now ScaledDecimal is de-serializing correctly 
this fixes #147 and #184

47-FractionodbSerialize-Why-do-we-not-call-register

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/BSDFLock.class.st
src/OmniBase/ByteSymbol.extension.st
src/OmniBase/FLock.class.st
src/OmniBase/ODBEncodingStream.class.st
src/OmniBase/ODBTypeCodes.class.st
src/OmniBase/WideSymbol.extension.st

This PR add a tests for wide symbol serialisation and fixes it.
I used the free code 48.
ODBWideSymbolCode := 48.
fixes #119

Fix wide symbol

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/Integer.extension.st
src/OmniBase/ODBEncodingStream.class.st

This PR makes sure that we register Large Integers (not large in the database sense, but large in the sense of the being instances of LargePositiveInteger or LargeNegativeInteger).
These are "normal" objects, and if we store them, we should store the second one as an internal reference. This way, identity is preserved and we save disk space to store these just once.
fixes #148

[to discuss] 48-IntegerodbSerialize-Why-do-we-not-call-register-LargePositiveNegative-Integers

---

src/OmniBase-Tests/ODBSerializationTest.class.st
src/OmniBase/ODBSerializer.class.st

When storing BlockClosure and Process, we used to silently just serialize the error message.
Instead, we should raise an error when storing so bugs are not hidden.
fixes #186

186-ODBSerializercantSave-does-not-raise-error-serialises-error-string
